[project]
name = "fastkitty"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.127.1",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.12.0",
    "uvicorn>=0.40.0",
    "sqlalchemy>=2.0.45",
    "ruff>=0.14.10",
    "psycopg2-binary>=2.9.11",
    "pyjwt>=2.11.0",
    "boto3>=1.34.0",
    "python-consul2>=0.1.5",
    "hvac>=2.3.0",
]
